[colors.primary]
background = "#303446" # Catppuccin Frappe background
foreground = "#C6D0F5"

[font]
size = 14

[font.offset]
y = 20

[font.glyph_offset]
y = 9

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.98
decorations = "none"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 120
lines = 40

[cursor]
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 2_000
