[font]
size = 20

  [font.offset]
  y = 24

  [font.glyph_offset]
  y = 9

  [font.normal]
  family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.98

  [window.padding]
  x = 5
  y = 5

  [window.dimensions]
  columns = 120
  lines = 40

[cursor]
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 2_000

